<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "js_paginate"
 *
 * Auto generated by Extension Builder 2016-03-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Paginate',
	'description' => 'Pagination extension provides the pagination for the custom extension records, News extension and other extensions',
	'category' => 'misc',
	'author' => 'Jainish Senjaliya',
	'author_email' => 'jainishsenjaliya@gmail.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '3.0.3',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0 - 8.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);